// Generated by CoffeeScript 1.3.3
var app, assets, cons, express, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

cons = require('consolidate');

app = express();

app.use(assets({
  src: 'client'
}));

app.use(express["static"](process.cwd() + '/shared'));

app.set('views', 'server/template');

app.engine('html', cons.jazz);

app.set('view engine', 'html');

js.root = 'code';

app.get('/', function(req, resp) {
  return resp.render('index', {
    variable: js('app')
  });
});

app.get('/:page', function(req, resp) {
  return resp.render(req.params.page, {
    variable: js('app')
  });
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
